### ISSUE TITLE
Separate insertion criteria from the rest of the callback

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/databroker-elasticsearch#15]
Should we separate the insertion criteria from the rest of the callback? It seems like something that could be implemented elsewhere (for instance as a filter step before calling the callback), which would give us more flexibility.

**Comment by pavoljuhas** [comment]
Does such filter step exist and is it ready for use at the beamlines?

If not I don't see any benefit in taking this extra work.

**Comment by CJ-Wright** [comment]
```python
from event_model import DocumentRouter

class Filter(DocumentRouter):
    def start(self, doc):
        # get the criteria from somewhere
        if not criteria(doc):
            # if it doesn't meet the criteria then pass empty thing
            return {}
```

**Comment by CJ-Wright** [comment]
I think the main benefit is one of separation, this way this repo does one thing well, inserting documents into elastic. The filtering is then an independent concern and can be dealt with more dynamically.

**Comment by pavoljuhas** [comment]
How would this rebuild the ES index when filtering function change?
Note that ElasticCallback has a rebuild function ready and tested just for that.

I agree the separation is cleaner, but brings an extra complexity on users/bm-scientists.
A bit of cleanup is not worth the extra effort and likelihood of new bugs.

**Comment by pavoljuhas** [comment]
Closing - not worth the effort at this time.
