### ISSUE TITLE
package name and import name

### ISSUE THREAD

**Issue by pavoljuhas** [NSLS-II/databroker-elasticsearch#2]
@CJ-Wright - I think we should use top level import name that is consistent with package name, i.e.,
can we rename `db_es` in #1 (1144cfb3f2a368464e66ccada9fda678da08584f) to  `databroker_elasticsearch`?

@tacaswell @danielballan @stuartcampbell - is there some naming convention for databroker add-ons?

**Comment by danielballan** [comment]
Informally, we seem to be following the pattern that you are advocating for here, e.g. the project name databroker-browser with a package named `databroker_browser`. :+1:

**Comment by CJ-Wright** [comment]
Personally I find that name a bit long, but would `databroker_es` could work?

**Comment by pavoljuhas** [comment]
I think it is better if repo name, package name and import name are all consistent.
Also `databroker_es` might imply Spanish localization of databroker.

**Comment by CJ-Wright** [comment]
I'm fine with making them consistent.
