### ISSUE TITLE
Naive question: has this working made contact with MongoDB River Plugin?

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/databroker-elasticsearch#7]
https://medium.com/@AzilenTech/integrating-elastic-search-with-mongodb-using-no-sql-6e67a8172a5a

**Comment by pavoljuhas** [comment]
We want to be agnostic of the database backend and only get data from databroker / bluesky APIs.

**Comment by danielballan** [comment]
Ah, I see. Thanks!
